"""drop inventory quantity

One row is one physical card. A `quantity` column beside a single scan, a
single condition and a single cost was a second and contradictory answer to
"how many cards is this row", and it is what made an inventory list of two
identical scans unexplainable.

Safe to drop here because it was never used: every row in every deployment
held 1. The check below refuses the migration if that is not true of the
database it is run against, rather than silently discarding a real count.

Downgrade restores the column with its old default, so stepping back leaves a
schema the previous release can run.

Revision ID: ab360b649e52
Revises: fd1c94a2fc8f
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "ab360b649e52"
down_revision = "fd1c94a2fc8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory", sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
