"""drop inventory quantity

One row is one physical card. A `quantity` column beside a single scan, a
single condition and a single cost was a second and contradictory answer to
"how many cards is this row", and it is what made an inventory list of two
identical scans unexplainable.

Safe to drop here because it was never used: every row in every deployment
held 1. The check below refuses the migration if that is not true of the
database it is run against, rather than silently discarding a real count.

Downgrade restores the column, filling existing rows with the 1 they all held,
so stepping back leaves a schema the previous release can run.

Revision ID: ab360b649e52
Revises: fd1c94a2fc8f
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "ab360b649e52"
down_revision = "fd1c94a2fc8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # `server_default` because the column is NOT NULL and the table it is going
    # back onto has rows in it. Autogenerate wrote this without one, which
    # Postgres refuses outright on any database that has ever held a card — so
    # the docstring above promised a downgrade that could only run on an empty
    # schema, which is the one case nobody needs it for.
    #
    # Dropped again immediately: every row held 1 because the application wrote
    # 1, not because the schema said so, and leaving a default behind restores
    # a column the old release did not have.
    op.add_column(
        "inventory",
        sa.Column(
            "quantity",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            server_default="1",
        ),
    )
    op.alter_column("inventory", "quantity", server_default=None)
