"""declared printing on inventory

Revision ID: d46268462eb9
Revises: 36ee08bea9f1
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "d46268462eb9"
down_revision = "36ee08bea9f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory", sa.Column("sub_type", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory", "sub_type")
    # ### end Alembic commands ###
