"""the name the source spells

Revision ID: 90f5ed7888a8
Revises: 7f2a91c4d3be

Autogenerate also proposed dropping `ix_cards_name_trgm` and clearing the
server default on `scans.size_bytes`. Both were declined. The first is a GIN
trigram index the model has no way to express, so every autogenerated revision
offers to remove it; the second is the backfill default a NOT NULL column
needed when it was added, and dropping it now would only make the next
revision offer to put it back.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "90f5ed7888a8"
down_revision = "7f2a91c4d3be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Nullable rather than backfilled from `name`. The two differ exactly where
    # this column matters — punctuation — so copying `name` across would fill
    # the catalogue with values that look right and join wrong. `foilstack
    # ingest` fills it in for real.
    op.add_column("cards", sa.Column("source_name", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("cards", "source_name")
