"""inventory finish, sold state and notes

`finish` and `status` are NOT NULL, and autogenerate emitted them without a
server default — which fails outright on any table that already has rows,
because Postgres has no value to put in them. A `server_default` gives the
existing rows one and is then dropped, so the column keeps its meaning
(the application always supplies a value) without the table ever being in a
state Postgres will not accept.

The defaults are the honest ones: a card is non-foil and in stock unless
somebody says otherwise.

Revision ID: fd1c94a2fc8f
Revises: a6e3135d319e
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "fd1c94a2fc8f"
down_revision = "a6e3135d319e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "import_jobs",
        sa.Column("default_finish", sa.String(length=16), nullable=False, server_default="nonfoil"),
    )
    op.add_column(
        "inventory",
        sa.Column("finish", sa.String(length=16), nullable=False, server_default="nonfoil"),
    )
    op.add_column("inventory", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "inventory",
        sa.Column("status", sa.String(length=16), nullable=False, server_default="stock"),
    )

    # Backfilled, so drop the database-side default: the application always
    # supplies these, and a server default left behind is a second source of
    # truth that silently disagrees the day the application's changes.
    op.alter_column("import_jobs", "default_finish", server_default=None)
    op.alter_column("inventory", "finish", server_default=None)
    op.alter_column("inventory", "status", server_default=None)
    op.add_column("inventory", sa.Column("sold_price", sa.Float(), nullable=True))
    op.add_column("inventory", sa.Column("sold_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("ix_inventory_user_status", "inventory", ["user_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inventory_user_status", table_name="inventory")
    op.drop_column("inventory", "sold_at")
    op.drop_column("inventory", "sold_price")
    op.drop_column("inventory", "status")
    op.drop_column("inventory", "notes")
    op.drop_column("inventory", "finish")
    op.drop_column("import_jobs", "default_finish")
    # ### end Alembic commands ###
