"""card prices, price history and sync state

Revision ID: 36ee08bea9f1
Revises: ab360b649e52
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "36ee08bea9f1"
down_revision = "ab360b649e52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_state",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("upstream_stamp", sa.Text(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_changed", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("source", "kind"),
    )
    op.create_table(
        "card_price_history",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("sub_type", sa.String(length=64), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("market", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("mid", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("card_id", "sub_type", "recorded_on"),
    )
    op.create_index(
        "ix_price_history_card", "card_price_history", ["card_id", "recorded_on"], unique=False
    )
    op.create_table(
        "card_prices",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("sub_type", sa.String(length=64), nullable=False),
        sa.Column("market", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("mid", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("card_id", "sub_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_prices")
    op.drop_index("ix_price_history_card", table_name="card_price_history")
    op.drop_table("card_price_history")
    op.drop_table("sync_state")
    # ### end Alembic commands ###
