"""scan best score

Revision ID: a6e3135d319e
Revises: ece6f4eba34c
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "a6e3135d319e"
down_revision = "ece6f4eba34c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("best_score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "best_score")
    # ### end Alembic commands ###
